### ISSUE TITLE
cart fall off when flying.

### ISSUE THREAD

**Issue by GreenForzeGaming** [jusipat/astikor-carts#12] opened 2024-03-22 21:09 UTC
i have ice and fire installed and i have a tamed hippogryph. ive added it too the config and the cart attaches just fine. it is when i start flying with it it just falls off. it was possible in the past and was very usefull. i dont know what causes this but id love a fix or a config that allowes Cart Flight.

**Comment by GreenForzeGaming** [comment] 2024-03-22 21:09
1.20.1 version 1.1.7

**Comment by jusipat** [comment] 2024-07-27 00:53
Duplicate of #8

**Closed as completed by jusipat** 2024-07-27 00:53 UTC
Labels: compat
