### ISSUE TITLE
astikor-carts-redux sound

### ISSUE THREAD

**Issue by bysbuild** [jusipat/astikor-carts#14] opened 2024-07-19 10:30 UTC
Hello, author, I remember the sound of the carriage in version 1.19; why is there no version 1.20 version? Can you add the feeling of being so immersed too much as soon as possible?

**Comment by jusipat** [comment] 2024-07-27 00:54
Duplicate of #7 
Currently looking into bringing back the sounds!

**Closed as completed by jusipat** 2024-07-27 00:54 UTC
